name: Load Data Regresion like artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'model2/simple_regresion.py'

jobs:
  load_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Actualizado a la versión 4
    - name: Set up Python
      uses: actions/setup-python@v3  # Actualizado a la versión 3
      id: setup
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run load.py
      run: python model2/simple_regresion.py --IdExecution ${{ github.run_number }}
